### PR TITLE
Update Twilio SDK and use newer endpoint

### PR DESCRIPTION
**Pull request by ineffyble**
This patch upgrades the version of Twilio SDK in use quite dramatically (to v5.13.0).

Upgrading allows us to use the newer [messages endpoint](https://www.twilio.com/docs/api/rest/message) instead of the deprecated [sms endpoint](https://www.twilio.com/docs/api/rest/sms). This should offer more potential in future, and offers these immediate benefits:

- Ability to send multi-segment SMS (longer than 160 characters). Currently, CiviSMS will allow you to compose a longer message, but will encounter a Twilio API error.
- Ability to send messages from an "alphanumeric sender ID", such as "CIVICRM" (in many countries), by changing the `From=` parameter in the provider set up.  _Note: One caveat of using this ability is Twilio will not be able to guess the recipient's country code, and must be provided with an internationalised number _

### CODE REVIEW

**Comment by spronay** [comment]
I just integrated this patch on our WP site, and that seems to have fixed a lot of what ailed us. THANK YOU! In a couple days, I'll check back and report how Twilio SDK v5.13.0 is performing.

**Comment by JohnFF** [comment]
Useful work @ineffyble, info.xml should be updated as well so that the PR can just be merged in.

**Comment by seamuslee001** [comment]
@spronay Any update on how the upgrade is performing?

**Comment by JohnFF** [comment]
@seamuslee001 Really well. Using it in a production instance now.

**Comment by totten** [comment]
That's 3 people now who've indicated that this change is good+working (@ineffyable, @spronay , @JohnFF), and no one is opposed. Nice. :)

@deepak-srivastava, are you still the maintainer here? (If so, I'll leave it to you. If not, then I could do a sort of NMU (borrowing from [Debian jargon](https://wiki.debian.org/NonMaintainerUpload)).

**Comment by ineffyble** [comment]
Any news on merging this?

**Comment by JohnFF** [comment]
@colemanw please can we merge this?

**Comment by JohnFF** [comment]
FYI - inbound messages work, but sometimes aren't matched to the users correctly. I'm thinking about building that fix into the Phone Number Validator.

**Comment by michaelmcandrew** [comment]
hi gang - should we also put out a new release based on this PR? I would be happy to do so if we agree it is a good idea, unless someone else wants to.

Does anyone know of any reasons why we shouldn't (or forever hold your peace)?

**Comment by seamuslee001** [comment]
I think that makes sense to me

**Comment by colemanw** [comment]
@ineffyble I'd be happy to make you a co-maintainer of this extension.

**Comment by michaelmcandrew** [comment]
I created a draft new version https://civicrm.org/extensions/twilio-sms-provider/version-121 and draft release https://github.com/civicrm/org.civicrm.sms.twilio/releases/edit/untagged-89bb7ba35ac8133b6d62. Happy to make this live if i get a couple of yays, and no nays...

**Comment by JohnFF** [comment]
I tried to be a top community guy and test this out, and instead got:

ACCESS DENIED
You are not authorized to access this page.

Even after logging in.

Suggestion: make a tag but not a release on GitHub. Then we can sync to
that and test it with not updating a release for everyone.

John

**Comment by michaelmcandrew** [comment]
hey there, the release is based on https://github.com/civicrm/org.civicrm.sms.twilio/commit/e1355645f7c1abbe1bc085b27217f578c05f5604 so rather than making another tag you could test that commit?  Then once we've happy, we can publish the two URLs I mentioned above.

I've tested it myself for outbound and inbound SMS on 4.7 on Drupal.

**Comment by michaelmcandrew** [comment]
Chatted with @seamuslee001 and am going to release this now...

**Comment by ineffyble** [comment]
@colemanw I'm not sure if I can commit much time to it, but sure - we'll be using Twilio a fair bit at my organisation going forward, and I have some ideas for features that it would be good to implement.

**Pull request merged**
